// apps/demo/src/ProviderConfig.tsx
import { useState } from "react";
import type {
  ProviderConfig,
  ProviderId,
  VercelSubProvider,
} from "./useProviderSend.js";

interface ProviderConfigProps {
  config: ProviderConfig;
  onChange: (patch: Partial<ProviderConfig>) => void;
}

export function ProviderConfigStrip({ config, onChange }: ProviderConfigProps) {
  const [collapsed, setCollapsed] = useState<boolean>(true);

  const statusLabel =
    config.provider === "mock"
      ? "Mock (scripted responses)"
      : config.provider === "openai-compatible"
        ? `openai-compatible: ${config.model || "(no model)"} @ ${config.baseURL || "(no url)"} · key ${config.apiKey ? `••••${config.apiKey.slice(-4)}` : "missing"}`
        : config.provider === "vercel"
          ? `vercel (${config.vercelSubProvider ?? "openai"}): ${config.model || "(no model)"} · key ${config.apiKey ? `••••${config.apiKey.slice(-4)}` : "missing"}`
          : `${config.provider}: ${config.model || "(no model)"} · key ${config.apiKey ? `••••${config.apiKey.slice(-4)}` : "missing"}`;

  if (collapsed) {
    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "6px 12px",
          fontSize: 12,
          background: "var(--sg-surface, #f3f4f6)",
          borderRadius: 6,
          border: "1px solid var(--sg-border, #e5e7eb)",
        }}
      >
        <span style={{ color: "var(--sg-muted, #6b7280)" }}>Provider:</span>
        <strong style={{ fontFamily: "ui-monospace, monospace" }}>
          {statusLabel}
        </strong>
        <button
          type="button"
          onClick={() => setCollapsed(false)}
          style={{
            marginLeft: "auto",
            padding: "2px 8px",
            fontSize: 12,
            background: "transparent",
            border: "1px solid var(--sg-border, #e5e7eb)",
            borderRadius: 4,
            cursor: "pointer",
          }}
        >
          Change
        </button>
      </div>
    );
  }

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 8,
        padding: 12,
        background: "var(--sg-surface, #f3f4f6)",
        borderRadius: 6,
        border: "1px solid var(--sg-border, #e5e7eb)",
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          flexWrap: "wrap",
        }}
      >
        <label
          style={{
            fontSize: 12,
            display: "flex",
            alignItems: "center",
            gap: 4,
          }}
        >
          Provider
          <select
            value={config.provider}
            onChange={(e) =>
              onChange({ provider: e.target.value as ProviderId })
            }
            style={{ padding: "4px 6px", fontSize: 12 }}
          >
            <option value="mock">Mock (scripted)</option>
            <option value="anthropic">Anthropic</option>
            <option value="openai">OpenAI</option>
            <option value="openai-compatible">
              OpenAI-compatible endpoint
            </option>
            <option value="gemini">Google Gemini</option>
            <option value="vercel">Vercel AI SDK</option>
          </select>
        </label>
        <label
          style={{
            fontSize: 12,
            display: "flex",
            alignItems: "center",
            gap: 4,
            flex: 1,
          }}
        >
          Model
          <input
            type="text"
            value={config.model}
            onChange={(e) => onChange({ model: e.target.value })}
            placeholder={config.provider === "mock" ? "(unused)" : "model name"}
            disabled={config.provider === "mock"}
            style={{ padding: "4px 6px", fontSize: 12, flex: 1 }}
          />
        </label>
        {config.provider === "vercel" && (
          <label
            style={{
              fontSize: 12,
              display: "flex",
              alignItems: "center",
              gap: 4,
            }}
          >
            Sub-provider
            <select
              value={config.vercelSubProvider ?? "openai"}
              onChange={(e) =>
                onChange({
                  vercelSubProvider: e.target.value as VercelSubProvider,
                })
              }
              style={{ padding: "4px 6px", fontSize: 12 }}
            >
              <option value="openai">OpenAI</option>
              <option value="anthropic">Anthropic</option>
              <option value="google">Google</option>
              <option value="mistral">Mistral</option>
              <option value="xai">xAI</option>
            </select>
          </label>
        )}
        {config.provider === "openai-compatible" && (
          <label
            style={{
              fontSize: 12,
              display: "flex",
              alignItems: "center",
              gap: 4,
              flex: 2,
            }}
          >
            baseURL
            <input
              type="text"
              value={config.baseURL ?? ""}
              onChange={(e) => onChange({ baseURL: e.target.value })}
              placeholder="https://api.groq.com/openai/v1"
              style={{ padding: "4px 6px", fontSize: 12, flex: 1 }}
            />
          </label>
        )}
        <label
          style={{
            fontSize: 12,
            display: "flex",
            alignItems: "center",
            gap: 4,
            flex: 2,
          }}
        >
          API key
          <input
            type="password"
            value={config.apiKey}
            onChange={(e) => onChange({ apiKey: e.target.value })}
            placeholder={config.provider === "mock" ? "(unused)" : "sk-..."}
            disabled={config.provider === "mock"}
            autoComplete="off"
            style={{ padding: "4px 6px", fontSize: 12, flex: 1 }}
          />
        </label>
        <button
          type="button"
          onClick={() => setCollapsed(true)}
          style={{
            padding: "4px 10px",
            fontSize: 12,
            background: "transparent",
            border: "1px solid var(--sg-border, #e5e7eb)",
            borderRadius: 4,
            cursor: "pointer",
          }}
        >
          Done
        </button>
      </div>
      {config.provider !== "mock" && (
        <div
          style={{
            fontSize: 11,
            color: "var(--sg-muted, #6b7280)",
            lineHeight: 1.4,
          }}
        >
          🔒 <strong>Dev testing only.</strong> Your key stays in{" "}
          <code>sessionStorage</code> and is sent directly from your browser to
          the provider.{" "}
          <strong>Production apps must proxy through a backend</strong> — never
          ship a key in your bundle.
        </div>
      )}
    </div>
  );
}

// apps/demo-vue/src/ProviderConfig.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type {
  ProviderConfig,
  ProviderId,
} from "./composables/useProviderSend.js";

const props = defineProps<{
  config: ProviderConfig;
}>();

const emit = defineEmits<{
  change: [patch: Partial<ProviderConfig>];
}>();

const collapsed = ref<boolean>(true);

const statusLabel = computed(() => {
  if (props.config.provider === "mock") return "Mock (scripted responses)";
  if (props.config.provider === "openai-compatible") {
    const key = props.config.apiKey
      ? `••••${props.config.apiKey.slice(-4)}`
      : "missing";
    const url = props.config.baseURL || "(no url)";
    return `openai-compatible: ${props.config.model || "(no model)"} @ ${url} · key ${key}`;
  }
  if (props.config.provider === "vercel") {
    const key = props.config.apiKey
      ? `••••${props.config.apiKey.slice(-4)}`
      : "missing";
    return `vercel (${props.config.vercelSubProvider ?? "openai"}): ${props.config.model || "(no model)"} · key ${key}`;
  }
  const key = props.config.apiKey
    ? `••••${props.config.apiKey.slice(-4)}`
    : "missing";
  return `${props.config.provider}: ${props.config.model || "(no model)"} · key ${key}`;
});

function onProviderChange(e: Event) {
  emit("change", {
    provider: (e.target as HTMLSelectElement).value as ProviderId,
  });
}
function onModelChange(e: Event) {
  emit("change", { model: (e.target as HTMLInputElement).value });
}
function onKeyChange(e: Event) {
  emit("change", { apiKey: (e.target as HTMLInputElement).value });
}
function onBaseURLChange(e: Event) {
  emit("change", { baseURL: (e.target as HTMLInputElement).value });
}
</script>

<template>
  <div v-if="collapsed" class="sg-provider-strip sg-provider-strip--collapsed">
    <span class="sg-provider-strip__label">Provider:</span>
    <strong class="sg-provider-strip__status">{{ statusLabel }}</strong>
    <button type="button" class="sg-provider-strip__toggle" @click="collapsed = false">
      Change
    </button>
  </div>
  <div v-else class="sg-provider-strip sg-provider-strip--expanded">
    <div class="sg-provider-strip__row">
      <label class="sg-provider-strip__field">
        Provider
        <select :value="config.provider" @change="onProviderChange">
          <option value="mock">Mock (scripted)</option>
          <option value="anthropic">Anthropic</option>
          <option value="openai">OpenAI</option>
          <option value="openai-compatible">OpenAI-compatible endpoint</option>
          <option value="gemini">Google Gemini</option>
          <option value="vercel">Vercel AI SDK</option>
        </select>
      </label>
      <label class="sg-provider-strip__field sg-provider-strip__field--grow">
        Model
        <input
          type="text"
          :value="config.model"
          @input="onModelChange"
          :placeholder="config.provider === 'mock' ? '(unused)' : 'model name'"
          :disabled="config.provider === 'mock'"
        />
      </label>
      <label v-if="config.provider === 'vercel'" class="sg-provider-strip__field">
        Sub-provider
        <select
          :value="config.vercelSubProvider ?? 'openai'"
          @change="(e) => emit('change', { vercelSubProvider: (e.target as HTMLSelectElement).value as any })"
        >
          <option value="openai">OpenAI</option>
          <option value="anthropic">Anthropic</option>
          <option value="google">Google</option>
          <option value="mistral">Mistral</option>
          <option value="xai">xAI</option>
        </select>
      </label>
      <label v-if="config.provider === 'openai-compatible'" class="sg-provider-strip__field sg-provider-strip__field--grow-2">
        baseURL
        <input
          type="text"
          :value="config.baseURL ?? ''"
          @input="onBaseURLChange"
          placeholder="https://api.groq.com/openai/v1"
        />
      </label>
      <label class="sg-provider-strip__field sg-provider-strip__field--grow-2">
        API key
        <input
          type="password"
          :value="config.apiKey"
          @input="onKeyChange"
          :placeholder="config.provider === 'mock' ? '(unused)' : 'sk-...'"
          :disabled="config.provider === 'mock'"
          autocomplete="off"
        />
      </label>
      <button type="button" class="sg-provider-strip__done" @click="collapsed = true">
        Done
      </button>
    </div>
    <div v-if="config.provider !== 'mock'" class="sg-provider-strip__notice">
      🔒 <strong>Dev testing only.</strong> Your key stays in <code>sessionStorage</code>
      and is sent directly from your browser to the provider.
      <strong>Production apps must proxy through a backend</strong> — never ship a key in your bundle.
    </div>
  </div>
</template>

<style scoped>
.sg-provider-strip {
  padding: 12px;
  background: var(--sg-surface, #f3f4f6);
  border-radius: 6px;
  border: 1px solid var(--sg-border, #e5e7eb);
  font-size: 12px;
}

.sg-provider-strip--collapsed {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
}

.sg-provider-strip--expanded {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.sg-provider-strip__label {
  color: var(--sg-muted, #6b7280);
}

.sg-provider-strip__status {
  font-family: ui-monospace, monospace;
}

.sg-provider-strip__toggle,
.sg-provider-strip__done {
  padding: 4px 10px;
  font-size: 12px;
  background: transparent;
  border: 1px solid var(--sg-border, #e5e7eb);
  border-radius: 4px;
  cursor: pointer;
}

.sg-provider-strip__toggle {
  margin-left: auto;
  padding: 2px 8px;
}

.sg-provider-strip__row {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.sg-provider-strip__field {
  display: flex;
  align-items: center;
  gap: 4px;
}

.sg-provider-strip__field--grow {
  flex: 1;
}

.sg-provider-strip__field--grow-2 {
  flex: 2;
}

.sg-provider-strip__field select,
.sg-provider-strip__field input {
  padding: 4px 6px;
  font-size: 12px;
}

.sg-provider-strip__field--grow input,
.sg-provider-strip__field--grow-2 input {
  flex: 1;
}

.sg-provider-strip__notice {
  font-size: 11px;
  color: var(--sg-muted, #6b7280);
  line-height: 1.4;
}
</style>
