// packages/react/src/editors/SelectEditor.tsx
import type { EditorRenderProps } from "../cells/types.js";

export function SelectEditor({
  value,
  column,
  onChange,
  onCommit,
  onCancel,
  error,
}: EditorRenderProps) {
  const options = column.selectOptions ?? [];

  return (
    <select
      className="eg-editor eg-select"
      // biome-ignore lint/a11y/noAutofocus: grid editor focus
      autoFocus
      value={value === null || value === undefined ? "" : String(value)}
      onChange={(e) => {
        const next = e.target.value;
        onChange(next);
        onCommit(next);
      }}
      onBlur={() => onCommit()}
      onKeyDown={(e) => {
        if (e.key === "Escape") {
          e.preventDefault();
          onCancel();
        }
      }}
      aria-invalid={error ? true : undefined}
      title={error}
    >
      <option value="">—</option>
      {options.map((o) => (
        <option key={o.value} value={o.value}>
          {o.label}
        </option>
      ))}
    </select>
  );
}

// packages/vue/src/editors/SelectEditor.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import type { EditorRenderProps } from "../cells/types.js";

const props = defineProps<EditorRenderProps>();
const selectRef = ref<HTMLSelectElement | null>(null);
let skipBlurCommit = false;

onMounted(() => {
  selectRef.value?.focus();
});

const display = computed(() =>
  props.value === null || props.value === undefined ? "" : String(props.value),
);

const options = computed(() => props.column.selectOptions ?? []);

function onChange(e: Event) {
  const next = (e.target as HTMLSelectElement).value;
  props.onChange(next);
  skipBlurCommit = true;
  props.onCommit(next);
}

function onBlur() {
  if (skipBlurCommit) return;
  props.onCommit();
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    e.preventDefault();
    skipBlurCommit = true;
    props.onCancel();
  }
}
</script>

<template>
  <select
    ref="selectRef"
    class="eg-editor eg-select"
    :value="display"
    :aria-invalid="error ? true : undefined"
    :title="error"
    @change="onChange"
    @blur="onBlur"
    @keydown="onKeyDown"
  >
    <option value="">—</option>
    <option v-for="o in options" :key="o.value" :value="o.value">{{ o.label }}</option>
  </select>
</template>
