// packages/react/src/AgentChat.tsx
import type {
  AgentError,
  AgentLoopOptions,
  AgentMessage,
  GridController,
  ToolCall,
} from "@sheetgrid/agent";
import type { OpResult } from "@sheetgrid/agent";
import { type CSSProperties, type ReactNode, useState } from "react";
import { useAgent } from "./useAgent.js";
import "./AgentChat.css";

export interface AgentChatProps {
  controller: GridController;
  send: AgentLoopOptions["send"];

  // Passthrough to useAgent
  onBeforeTool?: AgentLoopOptions["onBeforeTool"];
  onAfterTool?: AgentLoopOptions["onAfterTool"];
  maxHistory?: AgentLoopOptions["maxHistory"];
  toolFilter?: AgentLoopOptions["toolFilter"];
  systemPrompt?: AgentLoopOptions["systemPrompt"];
  maxIterations?: AgentLoopOptions["maxIterations"];

  // Styling
  className?: string;
  style?: CSSProperties;

  // Render-prop slots
  renderMessage?: (msg: AgentMessage) => ReactNode;
  renderToolTrace?: (call: ToolCall, result?: OpResult<unknown>) => ReactNode;
  renderInput?: (ctx: {
    send: (text: string) => void;
    thinking: boolean;
    cancel: () => void;
  }) => ReactNode;
  renderError?: (err: AgentError) => ReactNode;
  renderThinking?: () => ReactNode;

  // Event callbacks
  onSend?: (text: string) => void;
  onToolCall?: (call: ToolCall) => void;
  onDone?: () => void;
  onError?: (err: AgentError) => void;

  // Copy
  placeholder?: string;
  emptyState?: ReactNode;
}

function defaultRenderMessage(msg: AgentMessage): ReactNode {
  if (msg.role === "user") {
    return (
      <div key={msg.id} className="sg-agent-chat__msg sg-agent-chat__msg--user">
        {msg.content}
      </div>
    );
  }
  if (msg.role === "assistant") {
    return (
      <div
        key={msg.id}
        className="sg-agent-chat__msg sg-agent-chat__msg--assistant"
      >
        {msg.content.map((b, i) => {
          if (b.type === "text") return <span key={i}>{b.text}</span>;
          return (
            <div key={i} className="sg-agent-chat__tool">
              → {b.name}({JSON.stringify(b.input)})
            </div>
          );
        })}
      </div>
    );
  }
  // tool role
  return (
    <div key={msg.id} className="sg-agent-chat__tool">
      {msg.content.map((r, i) => (
        <div key={i}>
          ← {r.output.ok ? "ok" : `${r.output.code}: ${r.output.message}`}
        </div>
      ))}
    </div>
  );
}

export function AgentChat(props: AgentChatProps): JSX.Element {
  const {
    controller,
    send,
    onBeforeTool,
    onAfterTool,
    maxHistory,
    toolFilter,
    systemPrompt,
    maxIterations,
    className,
    style,
    renderMessage,
    renderInput,
    renderError,
    renderThinking,
    onSend,
    onToolCall,
    onDone,
    onError,
    placeholder = "Ask...",
    emptyState,
  } = props;

  const agent = useAgent(controller, {
    send,
    onBeforeTool,
    onAfterTool,
    maxHistory,
    toolFilter,
    systemPrompt,
    maxIterations,
    onError: (err) => {
      onError?.(err);
    },
  });

  const [text, setText] = useState("");

  // Wire event callbacks lazily on first render.
  const [wired, setWired] = useState(false);
  if (!wired) {
    if (onToolCall)
      agent.on(
        "tool.called",
        (e) => e.type === "tool.called" && onToolCall(e.call),
      );
    if (onDone) agent.on("done", () => onDone());
    setWired(true);
  }

  const doSend = (v: string) => {
    const clean = v.trim();
    if (!clean || agent.thinking) return;
    onSend?.(clean);
    setText("");
    void agent.send(clean);
  };

  return (
    <div
      className={`sg-agent-chat${className ? ` ${className}` : ""}`}
      style={style}
      role="log"
      aria-live="polite"
    >
      <div className="sg-agent-chat__transcript">
        {agent.messages.length === 0 && emptyState}
        {agent.messages.map((m) => (renderMessage ?? defaultRenderMessage)(m))}
        {agent.thinking &&
          (renderThinking ? (
            renderThinking()
          ) : (
            <div className="sg-agent-chat__thinking">thinking…</div>
          ))}
        {agent.error &&
          (renderError ? (
            renderError(agent.error)
          ) : (
            <div className="sg-agent-chat__error">
              {agent.error.code}: {agent.error.message}
            </div>
          ))}
      </div>
      {renderInput ? (
        renderInput({
          send: doSend,
          thinking: agent.thinking,
          cancel: agent.cancel,
        })
      ) : (
        <form
          className="sg-agent-chat__input"
          onSubmit={(e) => {
            e.preventDefault();
            doSend(text);
          }}
        >
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={placeholder}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                doSend(text);
              }
            }}
          />
          <button
            type="submit"
            disabled={agent.thinking || text.trim().length === 0}
          >
            Send
          </button>
          {agent.thinking && (
            <button type="button" onClick={agent.cancel}>
              Cancel
            </button>
          )}
        </form>
      )}
    </div>
  );
}

// packages/vue/src/AgentChat.vue
<script setup lang="ts">
import "./AgentChat.css";
import type {
  AgentError,
  AgentLoopOptions,
  AgentMessage,
  GridController,
  OpResult,
  ToolCall,
} from "@sheetgrid/agent";
import { ref } from "vue";
import { useAgent } from "./composables/useAgent.js";

const props = defineProps<{
  controller: GridController;
  send: AgentLoopOptions["send"];
  onBeforeTool?: AgentLoopOptions["onBeforeTool"];
  onAfterTool?: AgentLoopOptions["onAfterTool"];
  maxHistory?: AgentLoopOptions["maxHistory"];
  toolFilter?: AgentLoopOptions["toolFilter"];
  systemPrompt?: AgentLoopOptions["systemPrompt"];
  maxIterations?: AgentLoopOptions["maxIterations"];
  placeholder?: string;
}>();

const emit = defineEmits<{
  send: [text: string];
  "tool-call": [call: ToolCall];
  done: [];
  error: [error: AgentError];
}>();

defineSlots<{
  message?(props: { message: AgentMessage }): unknown;
  toolTrace?(props: { call: ToolCall; result?: OpResult<unknown> }): unknown;
  input?(props: {
    send: (text: string) => void;
    thinking: boolean;
    cancel: () => void;
  }): unknown;
  error?(props: { error: AgentError }): unknown;
  thinking?(): unknown;
  empty?(): unknown;
}>();

const agent = useAgent(props.controller, {
  send: props.send,
  onBeforeTool: props.onBeforeTool,
  onAfterTool: props.onAfterTool,
  maxHistory: props.maxHistory,
  toolFilter: props.toolFilter,
  systemPrompt: props.systemPrompt,
  maxIterations: props.maxIterations,
  onError: (err) => emit("error", err),
});

agent.on("tool.called", (e) => {
  if (e.type === "tool.called") emit("tool-call", e.call);
});
agent.on("done", () => emit("done"));

const text = ref("");

function doSend(v: string) {
  const clean = v.trim();
  if (!clean || agent.state.value.thinking) return;
  emit("send", clean);
  text.value = "";
  void agent.send(clean);
}

function onSubmit(e: Event) {
  e.preventDefault();
  doSend(text.value);
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    doSend(text.value);
  }
}
</script>

<template>
  <div class="sg-agent-chat" role="log" aria-live="polite">
    <div class="sg-agent-chat__transcript">
      <slot v-if="agent.state.value.messages.length === 0" name="empty" />
      <template v-for="m in agent.state.value.messages" :key="m.id">
        <slot name="message" :message="m">
          <div
            v-if="m.role === 'user'"
            class="sg-agent-chat__msg sg-agent-chat__msg--user"
          >{{ m.content }}</div>
          <div
            v-else-if="m.role === 'assistant'"
            class="sg-agent-chat__msg sg-agent-chat__msg--assistant"
          >
            <template v-for="(b, i) in m.content" :key="i">
              <span v-if="b.type === 'text'">{{ b.text }}</span>
              <div v-else class="sg-agent-chat__tool">
                → {{ b.name }}({{ JSON.stringify(b.input) }})
              </div>
            </template>
          </div>
          <div v-else class="sg-agent-chat__tool">
            <div v-for="(r, i) in m.content" :key="i">
              ← {{ r.output.ok ? "ok" : r.output.code + ": " + r.output.message }}
            </div>
          </div>
        </slot>
      </template>
      <slot v-if="agent.state.value.thinking" name="thinking">
        <div class="sg-agent-chat__thinking">thinking…</div>
      </slot>
      <template v-if="agent.state.value.error">
        <slot name="error" :error="agent.state.value.error">
          <div class="sg-agent-chat__error">
            {{ agent.state.value.error.code }}: {{ agent.state.value.error.message }}
          </div>
        </slot>
      </template>
    </div>
    <slot
      name="input"
      :send="doSend"
      :thinking="agent.state.value.thinking"
      :cancel="agent.cancel"
    >
      <form class="sg-agent-chat__input" @submit="onSubmit">
        <textarea
          v-model="text"
          :placeholder="placeholder ?? 'Ask...'"
          @keydown="onKeydown"
        />
        <button
          type="submit"
          :disabled="agent.state.value.thinking || text.trim().length === 0"
        >Send</button>
        <button
          v-if="agent.state.value.thinking"
          type="button"
          @click="agent.cancel"
        >Cancel</button>
      </form>
    </slot>
  </div>
</template>
