// packages/vue/src/editors/NumberEditor.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import type { EditorRenderProps } from "../cells/types.js";

const props = defineProps<EditorRenderProps>();
const inputRef = ref<HTMLInputElement | null>(null);
let skipBlurCommit = false;

onMounted(() => {
  inputRef.value?.focus();
});

const display =
  props.value === null || props.value === undefined ? "" : String(props.value);

function onInput(e: Event) {
  const raw = (e.target as HTMLInputElement).value;
  if (raw === "") {
    props.onChange(null);
    return;
  }
  const n = Number(raw);
  props.onChange(Number.isNaN(n) ? raw : n);
}

function onBlur() {
  if (skipBlurCommit) return;
  props.onCommit();
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    skipBlurCommit = true;
    props.onCommit();
  }
  if (e.key === "Escape") {
    e.preventDefault();
    skipBlurCommit = true;
    props.onCancel();
  }
}
</script>

<template>
  <input
    ref="inputRef"
    class="eg-editor"
    type="number"
    :value="display"
    :aria-invalid="error ? true : undefined"
    :title="error"
    @input="onInput"
    @blur="onBlur"
    @keydown="onKeyDown"
  />
</template>

// packages/react/src/editors/NumberEditor.tsx
import type { EditorRenderProps } from "../cells/types.js";

export function NumberEditor({
  value,
  onChange,
  onCommit,
  onCancel,
  error,
}: EditorRenderProps) {
  const display =
    value === null || value === undefined ? "" : String(value);

  return (
    <input
      className="eg-editor"
      type="number"
      // biome-ignore lint/a11y/noAutofocus: grid editor focus
      autoFocus
      value={display}
      onChange={(e) => {
        const raw = e.target.value;
        if (raw === "") {
          onChange(null);
          return;
        }
        const n = Number(raw);
        onChange(Number.isNaN(n) ? raw : n);
      }}
      onBlur={() => onCommit()}
      onKeyDown={(e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          onCommit();
        }
        if (e.key === "Escape") {
          e.preventDefault();
          onCancel();
        }
      }}
      aria-invalid={error ? true : undefined}
      title={error}
    />
  );
}
