// packages/vue/src/editors/TextEditor.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import type { EditorRenderProps } from "../cells/types.js";

const props = defineProps<EditorRenderProps>();
const inputRef = ref<HTMLInputElement | null>(null);
let skipBlurCommit = false;

onMounted(() => {
  inputRef.value?.focus();
});

const display =
  props.value === null || props.value === undefined ? "" : String(props.value);

function onInput(e: Event) {
  const target = e.target as HTMLInputElement;
  props.onChange(target.value);
}

function onBlur() {
  if (skipBlurCommit) return;
  props.onCommit();
}

function onKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    skipBlurCommit = true;
    props.onCommit();
  }
  if (e.key === "Escape") {
    e.preventDefault();
    skipBlurCommit = true;
    props.onCancel();
  }
}
</script>

<template>
  <input
    ref="inputRef"
    class="eg-editor"
    :value="display"
    :aria-invalid="error ? true : undefined"
    :title="error"
    @input="onInput"
    @blur="onBlur"
    @keydown="onKeyDown"
  />
</template>

// packages/react/src/editors/TextEditor.tsx
import type { EditorRenderProps } from "../cells/types.js";

export function TextEditor({
  value,
  onChange,
  onCommit,
  onCancel,
  error,
}: EditorRenderProps) {
  return (
    <input
      className="eg-editor"
      // biome-ignore lint/a11y/noAutofocus: grid editor focus
      autoFocus
      value={value === null || value === undefined ? "" : String(value)}
      onChange={(e) => onChange(e.target.value)}
      onBlur={() => onCommit()}
      onKeyDown={(e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          onCommit();
        }
        if (e.key === "Escape") {
          e.preventDefault();
          onCancel();
        }
      }}
      aria-invalid={error ? true : undefined}
      title={error}
    />
  );
}
