// packages/vue/src/cells/BooleanCell.vue
<script setup lang="ts">
import { computed } from "vue";
import type { CellRenderProps } from "./types.js";

const props = defineProps<CellRenderProps>();

const checked = computed(() => Boolean(props.value));

const disabled = computed(() => {
  const e = props.column.editable;
  if (e === undefined) return false;
  if (typeof e === "function") return false;
  return !e;
});

function onChange(event: Event) {
  event.stopPropagation();
  const target = event.target as HTMLInputElement;
  props.onCommitValue(target.checked);
}

function stop(event: Event) {
  event.stopPropagation();
}
</script>

<template>
  <input
    type="checkbox"
    class="eg-checkbox"
    :checked="checked"
    :disabled="disabled"
    :aria-label="String(column.header ?? column.id)"
    @change="onChange"
    @click="stop"
    @mousedown="stop"
  />
</template>

// packages/react/src/cells/BooleanCell.tsx
import type { CellRenderProps } from "./types.js";

export function BooleanCell({ value, onCommitValue, column }: CellRenderProps) {
  const checked = Boolean(value);
  const editable =
    column.editable === undefined
      ? true
      : typeof column.editable === "function"
        ? true
        : column.editable;

  return (
    <input
      type="checkbox"
      className="eg-checkbox"
      checked={checked}
      disabled={!editable}
      onChange={(e) => {
        e.stopPropagation();
        onCommitValue(e.target.checked);
      }}
      onClick={(e) => e.stopPropagation()}
      onMouseDown={(e) => e.stopPropagation()}
      aria-label={column.header}
    />
  );
}
